### ISSUE TITLE
群晖 docker ci/cd

### ISSUE THREAD

**Issue by yz-xlame** [yz-xlame/personal-diary#24]
## 进入gitlab的bash
- 双击容器，在"终端机"种新增bash
- ``` docker exec -it container_name bash```

## 修改gitlab配置文件
- gitlab.yml
- gitlab.rb

## 更新配置
```
gitlab-ctl reconfigure
```

**Comment by yz-xlame** [comment]
## 邮箱
gitlab_rails['gitlab_email_enabled'] = true
gitlab_rails['gitlab_email_from'] = 'example@163.com'
gitlab_rails['gitlab_email_display_name'] = 'admin' 
gitlab_rails['gitlab_email_reply_to'] = 'example@163.com'

gitlab_rails['smtp_enable'] = true
gitlab_rails['smtp_address'] = "smtp.163.com"
gitlab_rails['smtp_port'] = 465
gitlab_rails['smtp_user_name'] = "example@163.com"
gitlab_rails['smtp_password'] = "example"
gitlab_rails['smtp_domain'] = "163.com"
gitlab_rails['smtp_authentication'] = "login"
gitlab_rails['smtp_enable_starttls_auto'] = true
gitlab_rails['smtp_tls'] = true

gitlab_rails['smtp_openssl_verify_mode'] = 'none'

**Comment by yz-xlame** [comment]
## gitlab-runner
- [install runner](https://docs.gitlab.com/runner/install/)
- [register](https://docs.gitlab.com/runner/register/index.html#docker)
    - ip 输入为本地ip加端口
    - token为gitlab的runner registration  token
    - 描述与tag随便写
    - [executor](https://docs.gitlab.com/runner/executors/README.html)(Runner执行器)选择对应需要的
    - [docker镜像](https://docs.gitlab.com/runner/install/docker.html)
    - 因为是群晖，docker，getlab,http服务都在上面，所以[映射本地目录](https://docs.gitlab.com/runner/configuration/advanced-configuration.html#volumes-in-the-runnersdocker-section)到runner，之后用作http服务器目录
 重启runner后刷新gitlab runners即可看到runner

## setting options
- 发现runner的clone项目路径有问题导致报错,所以参考[文档](https://docs.gitlab.com/runner/configuration/advanced-configuration.html)修改clone_url
- 添加权限`privileged`

**Comment by yz-xlame** [comment]
## docker
- [document](https://docs.docker.com/get-started/overview/)
- 关于[volume](https://docs.docker.com/engine/reference/commandline/volume_create/)

## ci.yaml
- [document](https://docs.gitlab.com/ee/ci/yaml/README.html#stage)
- 关于cache的[建议](https://docs.gitlab.com/ee/ci/caching/)
- [翻译指北](https://www.ituring.com.cn/article/507812)
- [一篇实操](https://www.cnblogs.com/newton/archive/2021/01/21/14035169.html)
- 因为之前映射了本地目录到runner，所以没有添加artificts,直接使用本地http目录做build后的mv

## bash color
- [document](https://misc.flogisoft.com/bash/tip_colors_and_formatting)

## 练习最后的ci/cd
```
default:
  image: node:12-alpine

  # services
    # -

stages:
  - build
  - test
  # - deploy

# cache:
#   paths:
#     - node_modules
#     - build

logEnvironment:
  stage: .pre
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - node -v
    - npm -v

.build_stage:
  stage: build
  environment:
      name: production

build A:
  extends: .build_stage
  script:
    - echo "build A"
    # - npm install
    # - npm run build

build B 1/2:
  extends: .build_stage
  script:
    - echo "build B"
    # - npm install
    # - npm run build

build B 2/2:
  extends: .build_stage
  script:
    - echo "build B"
    # - npm install
    # - npm run build
    - rm -r ${DEPLOYMENT_PATH}/*
    - mv build/* /channel/
    - ls ${DEPLOYMENT_PATH}

test:
  stage: test
  script:
    - echo "Hello, $GLOBAL_HOST $GLOBAL_PORT $GLOBAL_WEB_PATH $DEPLOYMENT_PATH"
    - ls /channel
  # artifacts:
  #   paths:
  #     - index.html
  #   expire_in: 300s

# deploy:
#   stage: deploy
#   environment:
#       name: production

end:
  stage: .post
  script:
    - echo 'end'
```
